server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/image-file-service
    username: image-app-ar
    password: mmbp25
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # lets Hibernate create/update tables for you
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

aws:
  region: eu-north-1
  accessKeyId: YOUR_ACCESS_KEY_ID_HERE
  secretKey: YOUR_SECRET_KEY_HERE
  s3:
    bucketName: radnaskelar-image-service